import { randomUUID } from "node:crypto";
import type { MarketplaceItem } from "./marketplace.js";

export function getMarketplaceSeeds(): MarketplaceItem[] {
  const now = new Date().toISOString();

  return [
    // --- Skill Templates ---
    {
      id: randomUUID(),
      name: "SaaS Marketing Playbook",
      slug: "saas-marketing-playbook",
      category: "skill",
      author: "Paperclip Team",
      description: "Complete marketing playbook for SaaS products — acquisition funnels, trial optimization, churn reduction, and expansion revenue strategies.",
      longDescription: "A comprehensive skill that equips your marketing agents with proven SaaS growth frameworks. Includes templates for onboarding email sequences, trial-to-paid conversion flows, NPS-driven retention campaigns, and upsell/cross-sell playbooks. Built from analysis of 200+ successful SaaS companies.",
      version: "1.2.0",
      changelog: "v1.2.0: Added PLG motion templates\nv1.1.0: Churn prediction signals\nv1.0.0: Initial release",
      icon: "📊",
      rating: 4.8,
      ratingCount: 124,
      installCount: 892,
      tags: ["saas", "growth", "acquisition", "retention", "playbook"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: randomUUID(),
      name: "E-commerce Growth Kit",
      slug: "ecommerce-growth-kit",
      category: "skill",
      author: "Paperclip Team",
      description: "End-to-end e-commerce marketing toolkit — product feeds, dynamic ads, cart recovery, and seasonal campaign planning.",
      longDescription: "Transform your agents into e-commerce marketing experts. This kit includes product catalog optimization, dynamic remarketing setup, abandoned cart recovery sequences, seasonal sale planning calendars, and cross-channel attribution models. Supports Shopify, WooCommerce, and custom platforms.",
      version: "2.0.1",
      changelog: "v2.0.1: Fix Shopify metafield sync\nv2.0.0: Multi-platform support\nv1.0.0: Initial release",
      icon: "🛒",
      rating: 4.6,
      ratingCount: 89,
      installCount: 654,
      tags: ["ecommerce", "shopify", "ads", "cart-recovery", "growth"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: randomUUID(),
      name: "B2B Lead Gen",
      slug: "b2b-lead-gen",
      category: "skill",
      author: "Paperclip Team",
      description: "B2B lead generation system with ICP targeting, outbound sequences, LinkedIn automation, and pipeline scoring.",
      longDescription: "Automate your entire B2B pipeline. Define ideal customer profiles, generate targeted prospect lists, craft personalized outbound sequences, manage LinkedIn engagement, and score leads based on behavioral signals. Integrates with popular CRMs for seamless handoff to sales.",
      version: "1.4.0",
      changelog: "v1.4.0: LinkedIn engagement tracking\nv1.3.0: CRM sync improvements\nv1.0.0: Initial release",
      icon: "🎯",
      rating: 4.7,
      ratingCount: 156,
      installCount: 1203,
      tags: ["b2b", "lead-gen", "outbound", "linkedin", "pipeline"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: randomUUID(),
      name: "Content Marketing Machine",
      slug: "content-marketing-machine",
      category: "skill",
      author: "Paperclip Team",
      description: "Automated content strategy — editorial calendars, SEO-optimized briefs, distribution workflows, and performance analytics.",
      longDescription: "Build a content engine that runs on autopilot. Generates keyword-driven editorial calendars, produces SEO-optimized content briefs, manages multi-channel distribution (blog, social, email, syndication), and tracks content performance with attribution to revenue.",
      version: "1.1.0",
      changelog: "v1.1.0: Added content repurposing workflows\nv1.0.0: Initial release",
      icon: "✍️",
      rating: 4.5,
      ratingCount: 78,
      installCount: 567,
      tags: ["content", "seo", "editorial", "blogging", "distribution"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: randomUUID(),
      name: "Product Hunt Launch",
      slug: "product-hunt-launch",
      category: "skill",
      author: "Paperclip Team",
      description: "Complete Product Hunt launch playbook — pre-launch community building, launch day coordination, and post-launch momentum.",
      longDescription: "Everything you need for a top-5 Product Hunt launch. Pre-launch checklist spanning 4 weeks of community warming, maker profile optimization, hunter outreach templates, launch day hour-by-hour coordination plan, comment engagement strategies, and post-launch follow-up sequences.",
      version: "1.0.0",
      changelog: "v1.0.0: Initial release",
      icon: "🚀",
      rating: 4.9,
      ratingCount: 45,
      installCount: 312,
      tags: ["product-hunt", "launch", "community", "pr", "startup"],
      createdAt: now,
      updatedAt: now,
    },

    // --- Agent Templates ---
    {
      id: randomUUID(),
      name: "Growth Hacker",
      slug: "growth-hacker",
      category: "agent_template",
      author: "Paperclip Team",
      description: "Autonomous growth agent that runs experiments, analyzes metrics, and optimizes acquisition channels across paid and organic.",
      longDescription: "Deploy a growth-focused agent that continuously runs A/B tests, monitors key metrics (CAC, LTV, conversion rates), identifies winning channels, and reallocates budget to top performers. Comes pre-configured with experiment frameworks, statistical significance calculators, and automated reporting.",
      version: "2.1.0",
      changelog: "v2.1.0: Multi-variate testing support\nv2.0.0: Budget optimization engine\nv1.0.0: Initial release",
      icon: "📈",
      rating: 4.7,
      ratingCount: 203,
      installCount: 1567,
      tags: ["growth", "experiments", "optimization", "agent", "automation"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: randomUUID(),
      name: "SEO Specialist Pro",
      slug: "seo-specialist-pro",
      category: "agent_template",
      author: "Paperclip Team",
      description: "Advanced SEO agent handling technical audits, keyword research, content optimization, and backlink strategy.",
      longDescription: "A specialized SEO agent that performs comprehensive technical audits, identifies high-opportunity keywords, optimizes existing content for search intent, builds topical authority clusters, and manages link-building campaigns. Monitors SERP positions and adapts strategy based on algorithm updates.",
      version: "1.3.0",
      changelog: "v1.3.0: Core Web Vitals monitoring\nv1.2.0: Topical authority mapping\nv1.0.0: Initial release",
      icon: "🔍",
      rating: 4.6,
      ratingCount: 167,
      installCount: 1089,
      tags: ["seo", "technical-seo", "keywords", "backlinks", "agent"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: randomUUID(),
      name: "Social Media Manager Pro",
      slug: "social-media-manager-pro",
      category: "agent_template",
      author: "Paperclip Team",
      description: "Multi-platform social media agent managing content calendars, engagement, analytics, and community building.",
      longDescription: "Deploy an agent that manages your entire social presence. Creates platform-specific content calendars, generates posts optimized for each channel (Twitter/X, LinkedIn, Instagram, TikTok), monitors engagement and responds to comments, tracks follower growth, and identifies trending topics to capitalize on.",
      version: "1.5.0",
      changelog: "v1.5.0: TikTok strategy module\nv1.4.0: LinkedIn thought leadership\nv1.0.0: Initial release",
      icon: "📱",
      rating: 4.4,
      ratingCount: 134,
      installCount: 945,
      tags: ["social-media", "content", "engagement", "community", "agent"],
      createdAt: now,
      updatedAt: now,
    },

    // --- Plugins (Installable) ---
    {
      id: randomUUID(),
      name: "WhatsApp Gateway (Baileys)",
      slug: "whatsapp-gateway",
      category: "integration",
      author: "Paperclip Team",
      description: "Connect WhatsApp to your agents — scan a QR code, no Business API needed. Agents can send messages, request approvals, and deliver dashboards via WhatsApp.",
      longDescription: "Communication backbone for the Paperclip marketing platform. Uses Baileys (WhatsApp Web reverse-engineered protocol) to connect your personal WhatsApp number. Agents get tools to send messages, ask questions and wait for replies, request approvals (reply 1/2/3), send formatted KPI dashboards, and push notifications. QR code authentication — no Meta Business account or third-party service required.",
      version: "0.2.0",
      changelog: "v0.2.0: Rewritten from Cloud API to Baileys — QR code auth, no Business API\nv0.1.0: Initial WhatsApp Business Cloud API version",
      icon: "💬",
      rating: 4.7,
      ratingCount: 42,
      installCount: 287,
      tags: ["whatsapp", "messaging", "communication", "notifications", "approvals", "plugin"],
      createdAt: now,
      updatedAt: now,
    },

    // --- Integrations ---
    {
      id: randomUUID(),
      name: "Google Ads Pro",
      slug: "google-ads-pro",
      category: "integration",
      author: "Paperclip Team",
      description: "Deep Google Ads integration — campaign management, bid optimization, keyword sync, and automated reporting.",
      longDescription: "Connect your Google Ads account for full bidirectional sync. Agents can create campaigns, adjust bids based on performance data, pause underperforming ad groups, generate keyword suggestions from search term reports, and produce detailed ROI dashboards. Supports Search, Display, Shopping, and Performance Max campaigns.",
      version: "3.0.0",
      changelog: "v3.0.0: Performance Max support\nv2.0.0: Automated bidding strategies\nv1.0.0: Initial release",
      icon: "🔷",
      rating: 4.8,
      ratingCount: 289,
      installCount: 2134,
      tags: ["google-ads", "ppc", "advertising", "integration", "reporting"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: randomUUID(),
      name: "Meta Ads Suite",
      slug: "meta-ads-suite",
      category: "integration",
      author: "Paperclip Team",
      description: "Full Meta advertising integration — Facebook & Instagram ads management, audience building, creative testing, and ROAS tracking.",
      longDescription: "Manage your entire Meta advertising ecosystem. Create and optimize campaigns across Facebook and Instagram, build custom and lookalike audiences, run creative A/B tests, track conversions with the Conversions API, and monitor ROAS in real-time. Includes automated budget allocation based on performance.",
      version: "2.2.0",
      changelog: "v2.2.0: Advantage+ campaign support\nv2.0.0: Conversions API integration\nv1.0.0: Initial release",
      icon: "🔵",
      rating: 4.5,
      ratingCount: 198,
      installCount: 1678,
      tags: ["meta", "facebook", "instagram", "advertising", "integration"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: randomUUID(),
      name: "Stripe Revenue Tracker",
      slug: "stripe-revenue-tracker",
      category: "integration",
      author: "Paperclip Team",
      description: "Stripe integration for revenue analytics — MRR tracking, churn analysis, cohort reports, and financial forecasting.",
      longDescription: "Connect Stripe for comprehensive revenue intelligence. Track MRR, ARR, churn rate, expansion revenue, and net revenue retention in real-time. Generate cohort analyses, customer lifetime value predictions, and financial forecasts. Agents use this data to optimize marketing spend against actual revenue impact.",
      version: "1.6.0",
      changelog: "v1.6.0: Revenue forecasting module\nv1.5.0: Cohort analysis\nv1.0.0: Initial release",
      icon: "💳",
      rating: 4.9,
      ratingCount: 312,
      installCount: 2456,
      tags: ["stripe", "revenue", "mrr", "analytics", "integration"],
      createdAt: now,
      updatedAt: now,
    },
  ];
}
